USE [master]
GO

/****** Object:  Database [HealthCare]    Script Date: 25-Jul-18 8:03:16 PM ******/
CREATE DATABASE [HealthCare]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'healthCare', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\healthCare.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'healthCare_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\healthCare_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HealthCare] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HealthCare].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HealthCare] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HealthCare] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HealthCare] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HealthCare] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HealthCare] SET ARITHABORT OFF 
GO

ALTER DATABASE [HealthCare] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HealthCare] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HealthCare] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HealthCare] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HealthCare] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HealthCare] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HealthCare] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HealthCare] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HealthCare] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HealthCare] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HealthCare] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HealthCare] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HealthCare] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HealthCare] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HealthCare] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HealthCare] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HealthCare] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HealthCare] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HealthCare] SET RECOVERY FULL 
GO

ALTER DATABASE [HealthCare] SET  MULTI_USER 
GO

ALTER DATABASE [HealthCare] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HealthCare] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HealthCare] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HealthCare] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [HealthCare] SET  READ_WRITE 
GO


USE [HealthCare]
GO

/****** Object:  Table [dbo].[Contacts]    Script Date: 25-Jul-18 8:02:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Contacts](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
	[Address] [nvarchar](1000) NULL,
	[Email] [nvarchar](100) NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[Status] [varchar](20) NULL,
 CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




